<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmPurchaseOrder', 'doctrine');

/**
 * BaseOhrmPurchaseOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $request_master_id
 * @property integer $request_id
 * @property integer $id
 * @property integer $vendor_id
 * @property integer $product_id
 * @property float $price
 * @property integer $recipient_id
 * @property timestamp $issued_date
 * @property timestamp $deadline
 * @property integer $requester_id
 * @property integer $approved_by
 * @property string $description
 * @property integer $quantity
 * @property string $transaction_number
 * @property integer $status
 * @property string $cancellation_reason
 * @property HsHrEmployee $HsHrEmployee
 * @property OhrmProduct $OhrmProduct
 * @property HsHrEmployee $HsHrEmployee_3
 * @property HsHrEmployee $HsHrEmployee_4
 * @property OhrmVendor $OhrmVendor
 * @property OhrmPurchaseRequest $OhrmPurchaseRequest
 * @property OhrmPurchaseRequestMaster $OhrmPurchaseRequestMaster
 * 
 * @method integer                   getRequestMasterId()           Returns the current record's "request_master_id" value
 * @method integer                   getRequestId()                 Returns the current record's "request_id" value
 * @method integer                   getId()                        Returns the current record's "id" value
 * @method integer                   getVendorId()                  Returns the current record's "vendor_id" value
 * @method integer                   getProductId()                 Returns the current record's "product_id" value
 * @method float                     getPrice()                     Returns the current record's "price" value
 * @method integer                   getRecipientId()               Returns the current record's "recipient_id" value
 * @method timestamp                 getIssuedDate()                Returns the current record's "issued_date" value
 * @method timestamp                 getDeadline()                  Returns the current record's "deadline" value
 * @method integer                   getRequesterId()               Returns the current record's "requester_id" value
 * @method integer                   getApprovedBy()                Returns the current record's "approved_by" value
 * @method string                    getDescription()               Returns the current record's "description" value
 * @method integer                   getQuantity()                  Returns the current record's "quantity" value
 * @method string                    getTransactionNumber()         Returns the current record's "transaction_number" value
 * @method integer                   getStatus()                    Returns the current record's "status" value
 * @method string                    getCancellationReason()        Returns the current record's "cancellation_reason" value
 * @method HsHrEmployee              getHsHrEmployee()              Returns the current record's "HsHrEmployee" value
 * @method OhrmProduct               getOhrmProduct()               Returns the current record's "OhrmProduct" value
 * @method HsHrEmployee              getHsHrEmployee3()             Returns the current record's "HsHrEmployee_3" value
 * @method HsHrEmployee              getHsHrEmployee4()             Returns the current record's "HsHrEmployee_4" value
 * @method OhrmVendor                getOhrmVendor()                Returns the current record's "OhrmVendor" value
 * @method OhrmPurchaseRequest       getOhrmPurchaseRequest()       Returns the current record's "OhrmPurchaseRequest" value
 * @method OhrmPurchaseRequestMaster getOhrmPurchaseRequestMaster() Returns the current record's "OhrmPurchaseRequestMaster" value
 * @method OhrmPurchaseOrder         setRequestMasterId()           Sets the current record's "request_master_id" value
 * @method OhrmPurchaseOrder         setRequestId()                 Sets the current record's "request_id" value
 * @method OhrmPurchaseOrder         setId()                        Sets the current record's "id" value
 * @method OhrmPurchaseOrder         setVendorId()                  Sets the current record's "vendor_id" value
 * @method OhrmPurchaseOrder         setProductId()                 Sets the current record's "product_id" value
 * @method OhrmPurchaseOrder         setPrice()                     Sets the current record's "price" value
 * @method OhrmPurchaseOrder         setRecipientId()               Sets the current record's "recipient_id" value
 * @method OhrmPurchaseOrder         setIssuedDate()                Sets the current record's "issued_date" value
 * @method OhrmPurchaseOrder         setDeadline()                  Sets the current record's "deadline" value
 * @method OhrmPurchaseOrder         setRequesterId()               Sets the current record's "requester_id" value
 * @method OhrmPurchaseOrder         setApprovedBy()                Sets the current record's "approved_by" value
 * @method OhrmPurchaseOrder         setDescription()               Sets the current record's "description" value
 * @method OhrmPurchaseOrder         setQuantity()                  Sets the current record's "quantity" value
 * @method OhrmPurchaseOrder         setTransactionNumber()         Sets the current record's "transaction_number" value
 * @method OhrmPurchaseOrder         setStatus()                    Sets the current record's "status" value
 * @method OhrmPurchaseOrder         setCancellationReason()        Sets the current record's "cancellation_reason" value
 * @method OhrmPurchaseOrder         setHsHrEmployee()              Sets the current record's "HsHrEmployee" value
 * @method OhrmPurchaseOrder         setOhrmProduct()               Sets the current record's "OhrmProduct" value
 * @method OhrmPurchaseOrder         setHsHrEmployee3()             Sets the current record's "HsHrEmployee_3" value
 * @method OhrmPurchaseOrder         setHsHrEmployee4()             Sets the current record's "HsHrEmployee_4" value
 * @method OhrmPurchaseOrder         setOhrmVendor()                Sets the current record's "OhrmVendor" value
 * @method OhrmPurchaseOrder         setOhrmPurchaseRequest()       Sets the current record's "OhrmPurchaseRequest" value
 * @method OhrmPurchaseOrder         setOhrmPurchaseRequestMaster() Sets the current record's "OhrmPurchaseRequestMaster" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmPurchaseOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_purchase_order');
        $this->hasColumn('request_master_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('request_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('vendor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('recipient_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('issued_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deadline', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('requester_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('approved_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('transaction_number', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cancellation_reason', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HsHrEmployee', array(
             'local' => 'approved_by',
             'foreign' => 'emp_number'));

        $this->hasOne('OhrmProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('HsHrEmployee as HsHrEmployee_3', array(
             'local' => 'recipient_id',
             'foreign' => 'emp_number'));

        $this->hasOne('HsHrEmployee as HsHrEmployee_4', array(
             'local' => 'requester_id',
             'foreign' => 'emp_number'));

        $this->hasOne('OhrmVendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmPurchaseRequest', array(
             'local' => 'request_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmPurchaseRequestMaster', array(
             'local' => 'request_master_id',
             'foreign' => 'id'));
    }
}