<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmQuotations', 'doctrine');

/**
 * BaseOhrmQuotations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vendor_id
 * @property integer $product_id
 * @property float $price
 * @property integer $recipient_id
 * @property timestamp $issued_date
 * @property timestamp $deadline
 * @property integer $requester_id
 * @property integer $approved_by
 * @property string $description
 * @property integer $quantity
 * @property string $transaction_number
 * @property string $term_of_payment
 * @property OhrmUser $OhrmUser
 * @property OhrmProduct $OhrmProduct
 * @property OhrmUser $OhrmUser_3
 * @property OhrmUser $OhrmUser_4
 * @property OhrmVendor $OhrmVendor
 * 
 * @method integer        getId()                 Returns the current record's "id" value
 * @method integer        getVendorId()           Returns the current record's "vendor_id" value
 * @method integer        getProductId()          Returns the current record's "product_id" value
 * @method float          getPrice()              Returns the current record's "price" value
 * @method integer        getRecipientId()        Returns the current record's "recipient_id" value
 * @method timestamp      getIssuedDate()         Returns the current record's "issued_date" value
 * @method timestamp      getDeadline()           Returns the current record's "deadline" value
 * @method integer        getRequesterId()        Returns the current record's "requester_id" value
 * @method integer        getApprovedBy()         Returns the current record's "approved_by" value
 * @method string         getDescription()        Returns the current record's "description" value
 * @method integer        getQuantity()           Returns the current record's "quantity" value
 * @method string         getTransactionNumber()  Returns the current record's "transaction_number" value
 * @method string         getTermOfPayment()      Returns the current record's "term_of_payment" value
 * @method OhrmUser       getOhrmUser()           Returns the current record's "OhrmUser" value
 * @method OhrmProduct    getOhrmProduct()        Returns the current record's "OhrmProduct" value
 * @method OhrmUser       getOhrmUser3()          Returns the current record's "OhrmUser_3" value
 * @method OhrmUser       getOhrmUser4()          Returns the current record's "OhrmUser_4" value
 * @method OhrmVendor     getOhrmVendor()         Returns the current record's "OhrmVendor" value
 * @method OhrmQuotations setId()                 Sets the current record's "id" value
 * @method OhrmQuotations setVendorId()           Sets the current record's "vendor_id" value
 * @method OhrmQuotations setProductId()          Sets the current record's "product_id" value
 * @method OhrmQuotations setPrice()              Sets the current record's "price" value
 * @method OhrmQuotations setRecipientId()        Sets the current record's "recipient_id" value
 * @method OhrmQuotations setIssuedDate()         Sets the current record's "issued_date" value
 * @method OhrmQuotations setDeadline()           Sets the current record's "deadline" value
 * @method OhrmQuotations setRequesterId()        Sets the current record's "requester_id" value
 * @method OhrmQuotations setApprovedBy()         Sets the current record's "approved_by" value
 * @method OhrmQuotations setDescription()        Sets the current record's "description" value
 * @method OhrmQuotations setQuantity()           Sets the current record's "quantity" value
 * @method OhrmQuotations setTransactionNumber()  Sets the current record's "transaction_number" value
 * @method OhrmQuotations setTermOfPayment()      Sets the current record's "term_of_payment" value
 * @method OhrmQuotations setOhrmUser()           Sets the current record's "OhrmUser" value
 * @method OhrmQuotations setOhrmProduct()        Sets the current record's "OhrmProduct" value
 * @method OhrmQuotations setOhrmUser3()          Sets the current record's "OhrmUser_3" value
 * @method OhrmQuotations setOhrmUser4()          Sets the current record's "OhrmUser_4" value
 * @method OhrmQuotations setOhrmVendor()         Sets the current record's "OhrmVendor" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmQuotations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_quotations');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('vendor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('recipient_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('issued_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deadline', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('requester_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('approved_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('transaction_number', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('term_of_payment', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmUser', array(
             'local' => 'approved_by',
             'foreign' => 'id'));

        $this->hasOne('OhrmProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmUser as OhrmUser_3', array(
             'local' => 'recipient_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmUser as OhrmUser_4', array(
             'local' => 'requester_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmVendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));
    }
}