<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmCategory', 'doctrine');

/**
 * BaseOhrmCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $OhrmBudget
 * @property Doctrine_Collection $OhrmProduct
 * @property Doctrine_Collection $OhrmPurchaseRequest
 * @property Doctrine_Collection $OhrmServices
 * @property Doctrine_Collection $OhrmVendorToCategory
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getCode()                 Returns the current record's "code" value
 * @method Doctrine_Collection getOhrmBudget()           Returns the current record's "OhrmBudget" collection
 * @method Doctrine_Collection getOhrmProduct()          Returns the current record's "OhrmProduct" collection
 * @method Doctrine_Collection getOhrmPurchaseRequest()  Returns the current record's "OhrmPurchaseRequest" collection
 * @method Doctrine_Collection getOhrmServices()         Returns the current record's "OhrmServices" collection
 * @method Doctrine_Collection getOhrmVendorToCategory() Returns the current record's "OhrmVendorToCategory" collection
 * @method OhrmCategory        setId()                   Sets the current record's "id" value
 * @method OhrmCategory        setName()                 Sets the current record's "name" value
 * @method OhrmCategory        setCode()                 Sets the current record's "code" value
 * @method OhrmCategory        setOhrmBudget()           Sets the current record's "OhrmBudget" collection
 * @method OhrmCategory        setOhrmProduct()          Sets the current record's "OhrmProduct" collection
 * @method OhrmCategory        setOhrmPurchaseRequest()  Sets the current record's "OhrmPurchaseRequest" collection
 * @method OhrmCategory        setOhrmServices()         Sets the current record's "OhrmServices" collection
 * @method OhrmCategory        setOhrmVendorToCategory() Sets the current record's "OhrmVendorToCategory" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmBudget', array(
             'local' => 'id',
             'foreign' => 'category'));

        $this->hasMany('OhrmProduct', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('OhrmPurchaseRequest', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('OhrmServices', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('OhrmVendorToCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}