<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmServices', 'doctrine');

/**
 * BaseOhrmServices
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property string $services
 * @property string $pic
 * @property OhrmCategory $OhrmCategory
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method integer      getCategoryId()   Returns the current record's "category_id" value
 * @method string       getServices()     Returns the current record's "services" value
 * @method string       getPic()          Returns the current record's "pic" value
 * @method OhrmCategory getOhrmCategory() Returns the current record's "OhrmCategory" value
 * @method OhrmServices setId()           Sets the current record's "id" value
 * @method OhrmServices setCategoryId()   Sets the current record's "category_id" value
 * @method OhrmServices setServices()     Sets the current record's "services" value
 * @method OhrmServices setPic()          Sets the current record's "pic" value
 * @method OhrmServices setOhrmCategory() Sets the current record's "OhrmCategory" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmServices extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_services');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('services', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('pic', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}