<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmPurchaseRequestMaster', 'doctrine');

/**
 * BaseOhrmPurchaseRequestMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $employee_number
 * @property date $date
 * @property HsHrEmployee $HsHrEmployee
 * @property Doctrine_Collection $OhrmPurchaseOrder
 * 
 * @method integer                   getId()                Returns the current record's "id" value
 * @method integer                   getEmployeeNumber()    Returns the current record's "employee_number" value
 * @method date                      getDate()              Returns the current record's "date" value
 * @method HsHrEmployee              getHsHrEmployee()      Returns the current record's "HsHrEmployee" value
 * @method Doctrine_Collection       getOhrmPurchaseOrder() Returns the current record's "OhrmPurchaseOrder" collection
 * @method OhrmPurchaseRequestMaster setId()                Sets the current record's "id" value
 * @method OhrmPurchaseRequestMaster setEmployeeNumber()    Sets the current record's "employee_number" value
 * @method OhrmPurchaseRequestMaster setDate()              Sets the current record's "date" value
 * @method OhrmPurchaseRequestMaster setHsHrEmployee()      Sets the current record's "HsHrEmployee" value
 * @method OhrmPurchaseRequestMaster setOhrmPurchaseOrder() Sets the current record's "OhrmPurchaseOrder" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmPurchaseRequestMaster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_purchase_request_master');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HsHrEmployee', array(
             'local' => 'employee_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmPurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'request_master_id'));
    }
}