<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmDepartment', 'doctrine');

/**
 * BaseOhrmDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $OhrmBudget
 * @property Doctrine_Collection $OhrmPurchaseRequest
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getCode()                Returns the current record's "code" value
 * @method Doctrine_Collection getOhrmBudget()          Returns the current record's "OhrmBudget" collection
 * @method Doctrine_Collection getOhrmPurchaseRequest() Returns the current record's "OhrmPurchaseRequest" collection
 * @method OhrmDepartment      setId()                  Sets the current record's "id" value
 * @method OhrmDepartment      setName()                Sets the current record's "name" value
 * @method OhrmDepartment      setCode()                Sets the current record's "code" value
 * @method OhrmDepartment      setOhrmBudget()          Sets the current record's "OhrmBudget" collection
 * @method OhrmDepartment      setOhrmPurchaseRequest() Sets the current record's "OhrmPurchaseRequest" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_department');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmBudget', array(
             'local' => 'id',
             'foreign' => 'department'));

        $this->hasMany('OhrmPurchaseRequest', array(
             'local' => 'id',
             'foreign' => 'department_id'));
    }
}