<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmProduct', 'doctrine');

/**
 * BaseOhrmProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $category_id
 * @property string $provider
 * @property string $specifications
 * @property OhrmCategory $OhrmCategory
 * @property Doctrine_Collection $OhrmPurchaseOrder
 * @property Doctrine_Collection $OhrmPurchaseRequest
 * @property Doctrine_Collection $OhrmQuotations
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method integer             getCategoryId()          Returns the current record's "category_id" value
 * @method string              getProvider()            Returns the current record's "provider" value
 * @method string              getSpecifications()      Returns the current record's "specifications" value
 * @method OhrmCategory        getOhrmCategory()        Returns the current record's "OhrmCategory" value
 * @method Doctrine_Collection getOhrmPurchaseOrder()   Returns the current record's "OhrmPurchaseOrder" collection
 * @method Doctrine_Collection getOhrmPurchaseRequest() Returns the current record's "OhrmPurchaseRequest" collection
 * @method Doctrine_Collection getOhrmQuotations()      Returns the current record's "OhrmQuotations" collection
 * @method OhrmProduct         setId()                  Sets the current record's "id" value
 * @method OhrmProduct         setName()                Sets the current record's "name" value
 * @method OhrmProduct         setCategoryId()          Sets the current record's "category_id" value
 * @method OhrmProduct         setProvider()            Sets the current record's "provider" value
 * @method OhrmProduct         setSpecifications()      Sets the current record's "specifications" value
 * @method OhrmProduct         setOhrmCategory()        Sets the current record's "OhrmCategory" value
 * @method OhrmProduct         setOhrmPurchaseOrder()   Sets the current record's "OhrmPurchaseOrder" collection
 * @method OhrmProduct         setOhrmPurchaseRequest() Sets the current record's "OhrmPurchaseRequest" collection
 * @method OhrmProduct         setOhrmQuotations()      Sets the current record's "OhrmQuotations" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_product');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('provider', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('specifications', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('OhrmPurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('OhrmPurchaseRequest', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('OhrmQuotations', array(
             'local' => 'id',
             'foreign' => 'product_id'));
    }
}