<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmPurchaseRequest', 'doctrine');

/**
 * BaseOhrmPurchaseRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $master_id
 * @property integer $id
 * @property integer $category_id
 * @property integer $product_id
 * @property float $quantity
 * @property float $price_range_bottom
 * @property float $price_range_top
 * @property integer $budget_department
 * @property integer $budget_category
 * @property integer $approved_by
 * @property date $approval_date
 * @property string $additional_detail
 * @property string $transaction_number
 * @property integer $status
 * @property string $rejection_reason
 * @property HsHrEmployee $HsHrEmployee
 * @property OhrmBudget $OhrmBudget
 * @property OhrmBudget $OhrmBudget_3
 * @property OhrmCategory $OhrmCategory
 * @property OhrmProduct $OhrmProduct
 * @property Doctrine_Collection $OhrmPurchaseOrder
 * @property Budget $Budget
 * 
 * @method integer             getMasterId()           Returns the current record's "master_id" value
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getCategoryId()         Returns the current record's "category_id" value
 * @method integer             getProductId()          Returns the current record's "product_id" value
 * @method float               getQuantity()           Returns the current record's "quantity" value
 * @method float               getPriceRangeBottom()   Returns the current record's "price_range_bottom" value
 * @method float               getPriceRangeTop()      Returns the current record's "price_range_top" value
 * @method integer             getBudgetDepartment()   Returns the current record's "budget_department" value
 * @method integer             getBudgetCategory()     Returns the current record's "budget_category" value
 * @method integer             getApprovedBy()         Returns the current record's "approved_by" value
 * @method date                getApprovalDate()       Returns the current record's "approval_date" value
 * @method string              getAdditionalDetail()   Returns the current record's "additional_detail" value
 * @method string              getTransactionNumber()  Returns the current record's "transaction_number" value
 * @method integer             getStatus()             Returns the current record's "status" value
 * @method string              getRejectionReason()    Returns the current record's "rejection_reason" value
 * @method HsHrEmployee        getHsHrEmployee()       Returns the current record's "HsHrEmployee" value
 * @method OhrmBudget          getOhrmBudget()         Returns the current record's "OhrmBudget" value
 * @method OhrmBudget          getOhrmBudget3()        Returns the current record's "OhrmBudget_3" value
 * @method OhrmCategory        getOhrmCategory()       Returns the current record's "OhrmCategory" value
 * @method OhrmProduct         getOhrmProduct()        Returns the current record's "OhrmProduct" value
 * @method Doctrine_Collection getOhrmPurchaseOrder()  Returns the current record's "OhrmPurchaseOrder" collection
 * @method Budget              getBudget()             Returns the current record's "Budget" value
 * @method OhrmPurchaseRequest setMasterId()           Sets the current record's "master_id" value
 * @method OhrmPurchaseRequest setId()                 Sets the current record's "id" value
 * @method OhrmPurchaseRequest setCategoryId()         Sets the current record's "category_id" value
 * @method OhrmPurchaseRequest setProductId()          Sets the current record's "product_id" value
 * @method OhrmPurchaseRequest setQuantity()           Sets the current record's "quantity" value
 * @method OhrmPurchaseRequest setPriceRangeBottom()   Sets the current record's "price_range_bottom" value
 * @method OhrmPurchaseRequest setPriceRangeTop()      Sets the current record's "price_range_top" value
 * @method OhrmPurchaseRequest setBudgetDepartment()   Sets the current record's "budget_department" value
 * @method OhrmPurchaseRequest setBudgetCategory()     Sets the current record's "budget_category" value
 * @method OhrmPurchaseRequest setApprovedBy()         Sets the current record's "approved_by" value
 * @method OhrmPurchaseRequest setApprovalDate()       Sets the current record's "approval_date" value
 * @method OhrmPurchaseRequest setAdditionalDetail()   Sets the current record's "additional_detail" value
 * @method OhrmPurchaseRequest setTransactionNumber()  Sets the current record's "transaction_number" value
 * @method OhrmPurchaseRequest setStatus()             Sets the current record's "status" value
 * @method OhrmPurchaseRequest setRejectionReason()    Sets the current record's "rejection_reason" value
 * @method OhrmPurchaseRequest setHsHrEmployee()       Sets the current record's "HsHrEmployee" value
 * @method OhrmPurchaseRequest setOhrmBudget()         Sets the current record's "OhrmBudget" value
 * @method OhrmPurchaseRequest setOhrmBudget3()        Sets the current record's "OhrmBudget_3" value
 * @method OhrmPurchaseRequest setOhrmCategory()       Sets the current record's "OhrmCategory" value
 * @method OhrmPurchaseRequest setOhrmProduct()        Sets the current record's "OhrmProduct" value
 * @method OhrmPurchaseRequest setOhrmPurchaseOrder()  Sets the current record's "OhrmPurchaseOrder" collection
 * @method OhrmPurchaseRequest setBudget()             Sets the current record's "Budget" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmPurchaseRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_purchase_request');
        $this->hasColumn('master_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('quantity', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('price_range_bottom', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('price_range_top', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('budget_department', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('budget_category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('approved_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('approval_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('additional_detail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('transaction_number', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rejection_reason', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HsHrEmployee', array(
             'local' => 'approved_by',
             'foreign' => 'emp_number'));

        $this->hasOne('OhrmBudget', array(
             'local' => 'budget_department',
             'foreign' => 'department'));

        $this->hasOne('OhrmBudget as OhrmBudget_3', array(
             'local' => 'budget_category',
             'foreign' => 'category'));

        $this->hasOne('OhrmCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasMany('OhrmPurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'request_id'));

        $this->hasOne('Budget', array(
             'local' => 'budget_category',
             'foreign' => 'category'));
    }
}