<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEmployeeEvent', 'doctrine');

/**
 * BaseOhrmEmployeeEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $employee_id
 * @property string $type
 * @property string $event
 * @property string $note
 * @property timestamp $created_date
 * @property string $created_by
 * 
 * @method integer           getEventId()      Returns the current record's "event_id" value
 * @method integer           getEmployeeId()   Returns the current record's "employee_id" value
 * @method string            getType()         Returns the current record's "type" value
 * @method string            getEvent()        Returns the current record's "event" value
 * @method string            getNote()         Returns the current record's "note" value
 * @method timestamp         getCreatedDate()  Returns the current record's "created_date" value
 * @method string            getCreatedBy()    Returns the current record's "created_by" value
 * @method OhrmEmployeeEvent setEventId()      Sets the current record's "event_id" value
 * @method OhrmEmployeeEvent setEmployeeId()   Sets the current record's "employee_id" value
 * @method OhrmEmployeeEvent setType()         Sets the current record's "type" value
 * @method OhrmEmployeeEvent setEvent()        Sets the current record's "event" value
 * @method OhrmEmployeeEvent setNote()         Sets the current record's "note" value
 * @method OhrmEmployeeEvent setCreatedDate()  Sets the current record's "created_date" value
 * @method OhrmEmployeeEvent setCreatedBy()    Sets the current record's "created_by" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEmployeeEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_employee_event');
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('event', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('note', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('created_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}