<?php

/**
 * HsHrJobtitEmpstatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrJobtitEmpstatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrJobtitEmpstatTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrJobtitEmpstat');
    }
}