<?php

/**
 * HsHrCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrCountryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrCountry');
    }
}