<?php

/**
 * HsHrEmpBasicsalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpBasicsalaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrEmpBasicsalaryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpBasicsalary');
    }
}