<?php

/**
 * HsHrEmpDependentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpDependentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrEmpDependentsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpDependents');
    }
}