<?php

/**
 * HsHrCustomExportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrCustomExportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrCustomExportTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrCustomExport');
    }
}