<?php

/**
 * HsHrEmployeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmployeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrEmployeeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmployee');
    }
}