<?php

/**
 * HsHrMailnotificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrMailnotificationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrMailnotificationsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrMailnotifications');
    }
}