<?php

/**
 * HsHrConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrConfigTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrConfig');
    }
}