<?php

/**
 * HsHrEmpWorkExperienceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpWorkExperienceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrEmpWorkExperienceTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpWorkExperience');
    }
}