<?php

/**
 * HsHrDistrictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrDistrictTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrDistrictTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrDistrict');
    }
}