<?php

/**
 * HsHrEmpSkillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpSkillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return HsHrEmpSkillTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpSkill');
    }
}