<?php

/**
 * OhrmHomePageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmHomePageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmHomePageTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmHomePage');
    }
}