<?php

/**
 * OhrmJobInterviewInterviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobInterviewInterviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobInterviewInterviewerTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobInterviewInterviewer');
    }
}