<?php

/**
 * OhrmPerformanceTrackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmPerformanceTrackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmPerformanceTrackTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmPerformanceTrack');
    }
}