<?php

/**
 * OhrmSelectedGroupFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmSelectedGroupFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmSelectedGroupFieldTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmSelectedGroupField');
    }
}