<?php

/**
 * OhrmDataGroupScreenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmDataGroupScreenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmDataGroupScreenTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmDataGroupScreen');
    }
}