<?php

/**
 * OhrmEmpEducationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmpEducationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmEmpEducationTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmpEducation');
    }
}