<?php

/**
 * OhrmOauthUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmOauthUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmOauthUserTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmOauthUser');
    }
}