<?php

/**
 * OhrmLeaveRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmLeaveRequestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveRequest');
    }
}