<?php

/**
 * OhrmOauthAuthorizationCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmOauthAuthorizationCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmOauthAuthorizationCodeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmOauthAuthorizationCode');
    }
}