<?php

/**
 * OhrmVendorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmVendorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmVendorTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmVendor');
    }
}