<?php

/**
 * OhrmTimesheetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmTimesheetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmTimesheetTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmTimesheet');
    }
}