<?php

/**
 * OhrmPurchaseOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmPurchaseOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmPurchaseOrderTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmPurchaseOrder');
    }
}