<?php

/**
 * OhrmKpiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmKpiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmKpiTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmKpi');
    }
}