<?php

/**
 * OhrmUserSelectionRuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmUserSelectionRuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmUserSelectionRuleTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmUserSelectionRule');
    }
}