<?php

/**
 * OhrmUserRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmUserRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmUserRoleTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmUserRole');
    }
}