<?php

/**
 * OhrmServicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmServicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmServicesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmServices');
    }
}