<?php

/**
 * OhrmDatapointTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmDatapointTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmDatapointTypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmDatapointType');
    }
}