<?php

/**
 * OhrmLeaveLeaveEntitlementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveLeaveEntitlementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmLeaveLeaveEntitlementTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveLeaveEntitlement');
    }
}