<?php

/**
 * OhrmPerformanceTrackerLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmPerformanceTrackerLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmPerformanceTrackerLogTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmPerformanceTrackerLog');
    }
}