<?php

/**
 * OhrmQuotationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmQuotationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmQuotationsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmQuotations');
    }
}