<?php

/**
 * OhrmJobCandidateVacancyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobCandidateVacancyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobCandidateVacancyTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobCandidateVacancy');
    }
}