<?php

/**
 * OhrmVendorToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmVendorToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmVendorToCategoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmVendorToCategory');
    }
}