<?php

/**
 * OhrmEmployeeWorkShiftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmployeeWorkShiftTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmEmployeeWorkShiftTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmployeeWorkShift');
    }
}