<?php

/**
 * OhrmReviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmReviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmReviewerTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmReviewer');
    }
}