<?php

/**
 * OhrmEmailProcessorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmailProcessorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmEmailProcessorTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmailProcessor');
    }
}