<?php

/**
 * OhrmReviewerGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmReviewerGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmReviewerGroupTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmReviewerGroup');
    }
}