<?php

/**
 * OhrmOpenidUserIdentityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmOpenidUserIdentityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmOpenidUserIdentityTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmOpenidUserIdentity');
    }
}