<?php

/**
 * OhrmPluginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmPluginTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmPluginTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmPlugin');
    }
}