<?php

/**
 * OhrmNationalityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmNationalityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmNationalityTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmNationality');
    }
}