<?php

/**
 * OhrmEmpTerminationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmpTerminationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmEmpTerminationTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmpTermination');
    }
}