<?php

/**
 * OhrmProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmProductTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmProduct');
    }
}