<?php

/**
 * OhrmFilterFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmFilterFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmFilterFieldTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmFilterField');
    }
}