<?php

/**
 * OhrmJobCandidateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobCandidateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobCandidateTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobCandidate');
    }
}