<?php

/**
 * OhrmJobVacancyAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobVacancyAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobVacancyAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobVacancyAttachment');
    }
}