<?php

/**
 * OhrmJobCandidateAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobCandidateAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobCandidateAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobCandidateAttachment');
    }
}