<?php

/**
 * OhrmLeaveStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmLeaveStatusTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveStatus');
    }
}