<?php

/**
 * OhrmPurchaseRequestMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmPurchaseRequestMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmPurchaseRequestMasterTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmPurchaseRequestMaster');
    }
}