<?php

/**
 * OhrmLoginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLoginTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmLoginTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLogin');
    }
}