<?php

/**
 * OhrmReviewerRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmReviewerRatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmReviewerRatingTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmReviewerRating');
    }
}