<?php

/**
 * OhrmJobInterviewAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobInterviewAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobInterviewAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobInterviewAttachment');
    }
}