<?php

/**
 * OhrmDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmDepartmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmDepartment');
    }
}