<?php

/**
 * OhrmOpenidProviderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmOpenidProviderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmOpenidProviderTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmOpenidProvider');
    }
}