<?php

/**
 * OhrmLeaveEntitlementTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveEntitlementTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmLeaveEntitlementTypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveEntitlementType');
    }
}