<?php

/**
 * OhrmCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmCustomerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmCustomerTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmCustomer');
    }
}