<?php

/**
 * OhrmEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmEmailTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmail');
    }
}