<?php

/**
 * OhrmWorkWeekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmWorkWeekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmWorkWeekTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmWorkWeek');
    }
}