<?php

/**
 * OhrmJobCandidateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobCandidateHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return OhrmJobCandidateHistoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobCandidateHistory');
    }
}