<?php

/**
 * PluginQuotationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginQuotationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginQuotationsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginQuotations');
    }
}