<?php

/**
 * PluginServicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginServicesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServices');
    }
}