<?php

/**
 * PluginPurchaseRequestMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPurchaseRequestMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginPurchaseRequestMasterTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPurchaseRequestMaster');
    }
}