<?php

/**
 * PluginPurchaseRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPurchaseRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginPurchaseRequestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPurchaseRequest');
    }
}