<?php

/**
 * PluginProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginProductTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProduct');
    }
}