<?php

/**
 * PluginBudgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBudgetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginBudgetTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBudget');
    }
}