<?php

/**
 * PluginVendorToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVendorToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginVendorToCategoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVendorToCategory');
    }
}