<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Budget', 'doctrine');

/**
 * BaseBudget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $department
 * @property integer $category
 * @property float $amount
 * @property date $issued_date
 * @property date $last_until
 * @property Subunit $Subunit
 * @property Category $Category
 * @property Doctrine_Collection $PurchaseRequest
 * @property Doctrine_Collection $PurchaseRequest_2
 * 
 * @method integer             getDepartment()        Returns the current record's "department" value
 * @method integer             getCategory()          Returns the current record's "category" value
 * @method float               getAmount()            Returns the current record's "amount" value
 * @method date                getIssuedDate()        Returns the current record's "issued_date" value
 * @method date                getLastUntil()         Returns the current record's "last_until" value
 * @method Subunit             getSubunit()           Returns the current record's "Subunit" value
 * @method Category            getCategory()          Returns the current record's "Category" value
 * @method Doctrine_Collection getPurchaseRequest()   Returns the current record's "PurchaseRequest" collection
 * @method Doctrine_Collection getPurchaseRequest2()  Returns the current record's "PurchaseRequest_2" collection
 * @method Budget              setDepartment()        Sets the current record's "department" value
 * @method Budget              setCategory()          Sets the current record's "category" value
 * @method Budget              setAmount()            Sets the current record's "amount" value
 * @method Budget              setIssuedDate()        Sets the current record's "issued_date" value
 * @method Budget              setLastUntil()         Sets the current record's "last_until" value
 * @method Budget              setSubunit()           Sets the current record's "Subunit" value
 * @method Budget              setCategory()          Sets the current record's "Category" value
 * @method Budget              setPurchaseRequest()   Sets the current record's "PurchaseRequest" collection
 * @method Budget              setPurchaseRequest2()  Sets the current record's "PurchaseRequest_2" collection
 * 
 * @package    orangehrm
 * @subpackage model\purchasing\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBudget extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_budget');
        $this->hasColumn('department', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('issued_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('last_until', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subunit', array(
             'local' => 'department',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category',
             'foreign' => 'id'));

        $this->hasMany('PurchaseRequest', array(
             'local' => 'department',
             'foreign' => 'budget_department'));

        $this->hasMany('OhrmPurchaseRequest as PurchaseRequest_2', array(
             'local' => 'category',
             'foreign' => 'budget_category'));
    }
}