<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VendorToCategory', 'doctrine');

/**
 * BaseVendorToCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vendor_id
 * @property integer $category_id
 * @property Category $Category
 * @property Vendor $Vendor
 * 
 * @method integer          getVendorId()    Returns the current record's "vendor_id" value
 * @method integer          getCategoryId()  Returns the current record's "category_id" value
 * @method Category         getCategory()    Returns the current record's "Category" value
 * @method Vendor           getVendor()      Returns the current record's "Vendor" value
 * @method VendorToCategory setVendorId()    Sets the current record's "vendor_id" value
 * @method VendorToCategory setCategoryId()  Sets the current record's "category_id" value
 * @method VendorToCategory setCategory()    Sets the current record's "Category" value
 * @method VendorToCategory setVendor()      Sets the current record's "Vendor" value
 * 
 * @package    orangehrm
 * @subpackage model\purchasing\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVendorToCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_vendor_to_category');
        $this->hasColumn('vendor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Vendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));
    }
}