<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Product', 'doctrine');

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $category_id
 * @property string $provider
 * @property string $specifications
 * @property Category $Category
 * @property Doctrine_Collection $PurchaseOrder
 * @property Doctrine_Collection $PurchaseRequest
 * @property Doctrine_Collection $Quotations
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getCategoryId()      Returns the current record's "category_id" value
 * @method string              getProvider()        Returns the current record's "provider" value
 * @method string              getSpecifications()  Returns the current record's "specifications" value
 * @method Category            getCategory()        Returns the current record's "Category" value
 * @method Doctrine_Collection getPurchaseOrder()   Returns the current record's "PurchaseOrder" collection
 * @method Doctrine_Collection getPurchaseRequest() Returns the current record's "PurchaseRequest" collection
 * @method Doctrine_Collection getQuotations()      Returns the current record's "Quotations" collection
 * @method Product             setId()              Sets the current record's "id" value
 * @method Product             setName()            Sets the current record's "name" value
 * @method Product             setCategoryId()      Sets the current record's "category_id" value
 * @method Product             setProvider()        Sets the current record's "provider" value
 * @method Product             setSpecifications()  Sets the current record's "specifications" value
 * @method Product             setCategory()        Sets the current record's "Category" value
 * @method Product             setPurchaseOrder()   Sets the current record's "PurchaseOrder" collection
 * @method Product             setPurchaseRequest() Sets the current record's "PurchaseRequest" collection
 * @method Product             setQuotations()      Sets the current record's "Quotations" collection
 * 
 * @package    orangehrm
 * @subpackage model\purchasing\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_product');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('provider', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('specifications', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('PurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('PurchaseRequest', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Quotations', array(
             'local' => 'id',
             'foreign' => 'product_id'));
    }
}