<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PurchaseRequestMaster', 'doctrine');

/**
 * BasePurchaseRequestMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $employee_number
 * @property date $date
 * @property Employee $Employee
 * @property Doctrine_Collection $PurchaseOrder
 * 
 * @method integer               getId()              Returns the current record's "id" value
 * @method integer               getEmployeeNumber()  Returns the current record's "employee_number" value
 * @method date                  getDate()            Returns the current record's "date" value
 * @method Employee              getEmployee()        Returns the current record's "Employee" value
 * @method Doctrine_Collection   getPurchaseOrder()   Returns the current record's "PurchaseOrder" collection
 * @method PurchaseRequestMaster setId()              Sets the current record's "id" value
 * @method PurchaseRequestMaster setEmployeeNumber()  Sets the current record's "employee_number" value
 * @method PurchaseRequestMaster setDate()            Sets the current record's "date" value
 * @method PurchaseRequestMaster setEmployee()        Sets the current record's "Employee" value
 * @method PurchaseRequestMaster setPurchaseOrder()   Sets the current record's "PurchaseOrder" collection
 * 
 * @package    orangehrm
 * @subpackage model\purchasing\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchaseRequestMaster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_purchase_request_master');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'employee_number',
             'foreign' => 'emp_number'));

        $this->hasMany('PurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'request_master_id'));
    }
}