<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Services', 'doctrine');

/**
 * BaseServices
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property string $services
 * @property string $pic
 * @property Category $Category
 * @property Doctrine_Collection $PurchaseOrder
 * @property Doctrine_Collection $PurchaseRequest
 * @property Doctrine_Collection $Quotations
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getCategoryId()      Returns the current record's "category_id" value
 * @method string              getServices()        Returns the current record's "services" value
 * @method string              getPic()             Returns the current record's "pic" value
 * @method Category            getCategory()        Returns the current record's "Category" value
 * @method Doctrine_Collection getPurchaseOrder()   Returns the current record's "PurchaseOrder" collection
 * @method Doctrine_Collection getPurchaseRequest() Returns the current record's "PurchaseRequest" collection
 * @method Doctrine_Collection getQuotations()      Returns the current record's "Quotations" collection
 * @method Services            setId()              Sets the current record's "id" value
 * @method Services            setCategoryId()      Sets the current record's "category_id" value
 * @method Services            setServices()        Sets the current record's "services" value
 * @method Services            setPic()             Sets the current record's "pic" value
 * @method Services            setCategory()        Sets the current record's "Category" value
 * @method Services            setPurchaseOrder()   Sets the current record's "PurchaseOrder" collection
 * @method Services            setPurchaseRequest() Sets the current record's "PurchaseRequest" collection
 * @method Services            setQuotations()      Sets the current record's "Quotations" collection
 * 
 * @package    orangehrm
 * @subpackage model\purchasing\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServices extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_services');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('services', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('pic', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('PurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'service_id'));

        $this->hasMany('PurchaseRequest', array(
             'local' => 'id',
             'foreign' => 'service_id'));

        $this->hasMany('Quotations', array(
             'local' => 'id',
             'foreign' => 'service_id'));
    }
}