<?php

/**
 * BudgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetTable extends PluginBudgetTable
{
    /**
     * Returns an instance of this class.
     *
     * @return BudgetTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Budget');
    }
}