<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends PluginProductTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ProductTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }
}