<?php

/**
 * PurchaseRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseRequestTable extends PluginPurchaseRequestTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PurchaseRequestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseRequest');
    }
}