<?php

/**
 * PurchaseOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseOrderTable extends PluginPurchaseOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PurchaseOrderTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseOrder');
    }
}