<?php

/**
 * PurchaseRequestMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseRequestMasterTable extends PluginPurchaseRequestMasterTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PurchaseRequestMasterTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseRequestMaster');
    }
}