<?php

/**
 * QuotationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuotationsTable extends PluginQuotationsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return QuotationsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quotations');
    }
}