<?php

/**
 * VendorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VendorTable extends PluginVendorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return VendorTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vendor');
    }
}