<?php

/**
 * VendorToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VendorToCategoryTable extends PluginVendorToCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return VendorToCategoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VendorToCategory');
    }
}