<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/03/02 07:09:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=bitnami_orangehrm',
  'username' => 'bn_orangehrm',
  'password' => '7fe1fc8ccd',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
